### PR TITLE
Fixes issue #181 by adjusting Float casting.

### PR DESCRIPTION
**Pull request by MikaylaRay44**
See issue #181 for details.

### CODE REVIEW

**Comment by mikeburke106** [comment]
This is a developer-facing breaking change that could break developer code.

```java
Float longitude = sendLocation.getLongitudeDegrees(); // won't compile after this change
```

If this is a change that really needs to be made, technically the methods with Float type should be deprecated and replaced so existing developer code isn't affected.  This also allows the change to be brought in in 4.* instead of 5.0 under semantic versioning.

**Comment by MikaylaRay44** [comment]
The problem with deprecating the getter and setter methods is that there will be library conflicts that won't compile.

```java
public Float getLongitudeDegrees()
public Double getLongitudeDegrees() // This will cause a conflict
```

However, the code will compile that you mentioned before, but it will cause a `ClassCastException` because you cannot cast a Double to a Float in that manner, you would need to call .floatValue() or change your current value to a Double.

So in light of that, even renaming the legacy code method will still cause this runtime exception to occur. Any ideas on how to solve that issue then? @mrapitis @mikeburke106

**Comment by mrapitis** [comment]
Can we please discuss further in our next PR review.

**Comment by mikeburke106** [comment]
@MikaylaRay44 Ahh, good point.  I don't think you have a choice, then, you'll have to make it a breaking change and it won't be able to be released until 5.0 under semantic versioning.  It also needs to be documented for developers to change their type to Double to fix the error that will be introduced in their code.

**Comment by mikeburke106** [comment]
Also, instead of doing your reflection (`instanceof`) in each of the methods, you should use the [SdlDataTypeConverter.objectToDouble method](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/util/SdlDataTypeConverter.java#L5-19) to be consistent with other classes.  Once the breaking change is made, you should no longer have to account for the floating point type.

**Pull request merged**
