### PR TITLE
Refactored RPC Design

### LINKED ISSUE #116: RPC classes should implement equals() and hashcode() methods
In order to compare RPC messages through the `equals()` method, each RPC has to override the `equals()` and `hashcode()` methods.  We need this ability for unit test and for general usability of the RPC classes.  

Eclipse can generate these methods from underlying class variables, but since the current RPC implementation doesn't store anything in class variables, it's all but impossible to implement this in the current design.  Once the feature/refactor_rpcs code is merged into develop, this effort can happen.

### PR DESCRIPTION
**Pull request by mikeburke106**
:boom: READY FOR REVIEW :boom:

Related to issue #20.
## Summary

We've gone over this in the past, but [this presentation](https://docs.google.com/a/livioradio.com/presentation/d/1BvbVJRm6wxPUFmGJsZMMQMgL7fK7CaeAzpgudepCT44/edit#slide=id.p) is probably the best explanation of what this pull request will accomplish.  Also, a similar (complete) codebase can be found on GENIVI [here](http://git.projects.genivi.org/?p=smartdevicelink_android.git;a=shortlog;h=refs/heads/feature/refactor_rpcs).

On a high level, this is what's going to happen:
1. Modify RPCStruct abstract class to implement JsonParameters interface and create RPCObject
2. Create JSONObjects from underlying data
3. Create constructors to create RPC objects from JSONObjects
4. Hashtable implementation is removed in favor of primitive variables and strings
5. Setter and getter methods in RPC classes will be re-written to return underlying variables instead of reading from the hashtable
6. Enums will implement JsonName interface, which allows decoupling the JSON keys from the actual variable names
7. Add versioning to any JSON related methods so correct JSON can be parsed and created based on the version of SDL

A utility class called JsonUtils has been created to allow one-line reads and writes to JSON objects.  The existing Android API throws an exception when reading from a JSON object when the input key doesn't exist.  The utility class wraps the API and returns null when an exception occurs.  Similarly, the Android API will throw an exception (and cause a crash) when attempting to place an invalid object into a JSON object.  The utility library catches and logs the exception so the app isn't forced to crash.
### Refactor RPCStruct into JsonParameters interface

The existing RPCStruct class doesn't really accomplish anything in and of itself other than creating the JSON structure based on the underlying hashtables.  As explained in the above presentation, this creates a tight coupling between the code and the JSON protocol structure, which makes the code inflexible and hard to change if the JSON protocol changes.  Similarly, if the JSON protocol changes, the abstract top-level RPCStruct class must modify it's underlying hashtables, which in turn affects all subclasses of RPCStruct (every RPC class).  The new implementation is simply an interface which requires any implementing class to create a JSONObject representing its underlying data.

A typical RPCMessage implementation of JsonParameters interface will look something like this:

``` java
@Override
public JSONObject getJsonParameters(int sdlVersion){
    // retrieve the JSON object from the parent and add our variables to it
    JSONObject result = super.getJsonParameters(sdlVersion);

    switch(sdlVersion){
    default:
        JsonUtils.addToJsonObject(result, KEY_TRY_AGAIN_TIME, this.tryAgainTime);
        break;
    }

    return result;
}
```

RPC "objects" (a.k.a. not requests, responses or notifications) will now subclass RPCObject, which implements JsonParameters interface on its own.  The implementation should read the JSON object from the superclass and put the class's underlying variables into the JSON object.

A common implementation of a RPC object will look something like this:

``` java
@Override
public JSONObject getJsonParameters(int sdlVersion){
    JSONObject result = super.getJsonParameters(sdlVersion);

    switch(sdlVersion){
    default:
        JsonUtils.addToJsonObject(result, KEY_AUDIO_TYPE, this.audioType);
        JsonUtils.addToJsonObject(result, KEY_BITS_PER_SAMPLE, this.bitsPerSample);
        JsonUtils.addToJsonObject(result, KEY_SAMPLING_RATE, this.samplingRate);
        break;
    }

    return result;
}
```
### Create JSON Methods

Any class that implements JsonParameters also needs to create a constructor that only takes in a JSONObject.  This constructor should read values from the JSONObject based on the SDL version and assigns the data to the individual underlying data.  This allows each class to "serialize" and "deserialize" the underlying data into a JSONObject.

A typical constructor will look something like this:

``` java
public AlertResponse(JSONObject jsonObject) {
    super(jsonObject);

    switch(sdlVersion){
    default:
        this.tryAgainTime = JsonUtils.readIntegerFromJsonObject(jsonObject, KEY_TRY_AGAIN_TIME);
        break;
    }
}
```

For performance reasons, when a class which contains enum values is created from a JSON object, the enum value will be stored locally as a string representation.  In the getter methods for any enum values, a reverse-lookup will be executed to determine the enum value based on the string value read from the JSON.  Similarly, in the setter methods for any enum values, the JsonName interface will allow the enum classes to define a JSON string based on whatever version of SDL is connected at the time.

Enums will typically be handled like this:

``` java
// constructor with enum values in the JSON object
public AudioPassThruCapabilities(JSONObject jsonObject, int sdlVersion){
    switch(sdlVersion){
    default:
        this.audioType = JsonUtils.readStringFromJsonObject(jsonObject, KEY_AUDIO_TYPE);
        break;
    }
}

public void setAudioType(AudioType audioType) {
    // use JsonName interface to produce the JSON name for the input enum value
    this.audioType = audioType.getJsonName(sdlVersion);
}

public AudioType getAudioType() {
    // perform reverse-lookup of string value to determine enum value
    return AudioType.valueForJsonName(this.audioType, sdlVersion);
}

@Override
public JSONObject getJsonParameters(int sdlVersion){
    JSONObject result = new JSONObject();

    switch(sdlVersion){
    default:
        // since the JSON string is already stored in the local variable, we can save it in the JSON directly
        JsonUtils.addToJsonObject(result, KEY_AUDIO_TYPE, this.audioType);
        break;
    }

    return result;
}
```
### Refactor Setter and Getter Methods

Current setter/getter methods read and put items into the underlying hashtables.  All of these methods will be refactored to simply return or set the underlying data based on typical Java object oriented design.

For example, the current code base has a getter method in [AddCommand.java](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/rpc/AddCommand.java):

``` java
public Image getCmdIcon() {
    Object obj = parameters.get(KEY_CMD_ICON);
    if (obj instanceof Image) {
        return (Image) obj;
    } else if (obj instanceof Hashtable) {
        try {
            return new Image((Hashtable<String, Object>) obj);
        } catch (Exception e) {
            DebugTool.logError("Failed to parse " + getClass().getSimpleName() + "." + KEY_CMD_ICON, e);
        }
    }
    return null;
}
```

This code will be refactored to simply return the underlying value representing the command icon:

``` java
public Image getCmdIcon() {
    return cmdIcon;
}
```

SImilarly, setter methods will use typical Java-style setter methods:

``` java
public void setCmdIcon(Image cmdIcon){
    this.cmdIcon = cmdIcon;
}
```
### Add Versioning

Any JSON-related methods need to take into account the connected version of SDL so they can build and decode the JSON messages appropriately for whatever version of SDL core it is connected to.  Constructors that take in a JSON object should also take in the SDL version and the JsonParameters interface will pass in the SDL version and return the resultant JSONObject.
##### General
- [x] Remove RPCStruct class and replace with JsonParameters interface
- [x] Create JSON structure in RPCMessage.java toJson() method
- [x] Remove JsonRPCMarshaller class since it is not needed in new design
- [x] Create SdlCommand enumeration with information about every possible RPC message that can be sent or received
- [x] Create BulkData interface for classes that utilize bulk data
- [x] Refactor the rest of the project to work with the new design
- [x] Run unit tests on completed refactored design
- [x] Fix #116 
- [ ] Merge develop into this PR to bring in changes made since PR was created
##### RPCs
- [x] Refactor RPC messages and objects
  - [x] Refactor AddCommand
  - [x] Refactor AddCommandResponse
  - [x] Refactor AddSubMenu
  - [x] Refactor AddSubMenuResponse
  - [x] Refactor AirbagStatus
  - [x] Refactor Alert
  - [x] Refactor AlertResponse
  - [x] Refactor AudioPassThruCapabilities
  - [x] Refactor BeltStatus
  - [x] Refactor BodyInformation
  - [x] Refactor ButtonCapabilities
  - [x] Refactor ChangeRegistration
  - [x] Refactor ChangeRegistrationResponse
  - [x] Refactor Choice
  - [x] Refactor ClusterModeStatus
  - [x] Refactor CreateInteractionChoiceSet
  - [x] Refactor CreateInteractionChoiceSetResponse
  - [x] Refactor DeleteCommand
  - [x] Refactor DeleteCommandResponse
  - [x] Refactor DeleteFile
  - [x] Refactor DeleteFileResponse
  - [x] Refactor DeleteInteractionChoiceSet
  - [x] Refactor DeleteInteractionChoiceSetResponse
  - [x] Refactor DeleteSubMenu
  - [x] Refactor DeleteSubMenuResponse
  - [x] Refactor DeviceInfo
  - [x] Refactor DeviceStatus
  - [x] Refactor DiagnosticMessage
  - [x] Refactor DiagnosticMessageResponse
  - [x] Refactor DIDResult
  - [x] Refactor DisplayCapabilities
  - [x] Refactor DTC
  - [x] Refactor ECallInfo
  - [x] Refactor EmergencyEvent
  - [x] Refactor EndAudioPassThru
  - [x] Refactor EndAudioPassThruResponse
  - [x] Refactor GenericResponse
  - [x] Refactor GetDTCs
  - [x] Refactor GetDTCsResponse
  - [x] Refactor GetVehicleData
  - [x] Refactor GetVehicleDataResponse
  - [x] Refactor GPSData
  - [x] Refactor Headers
  - [x] Refactor HeadLampStatus
  - [x] Refactor HMIPermissions
  - [x] Refactor Image
  - [x] Refactor ImageField
  - [x] Refactor ImageResolution
  - [x] Refactor KeyboardProperties
  - [x] Refactor ListFiles
  - [x] Refactor ListFilesResponse
  - [x] Refactor MenuParams
  - [x] Refactor MyKey
  - [x] Refactor OnAppInterfaceUnregistered
  - [x] Refactor OnAudioPassThru
  - [x] Refactor OnButtonEvent
  - [x] Refactor OnButtonPress
  - [x] Refactor OnCommand
  - [x] Refactor OnDriverDistraction
  - [x] Refactor OnHashChange
  - [x] Refactor OnHMIStatus
  - [x] Refactor OnKeyboardInput
  - [x] Refactor OnLanguageChange
  - [x] Refactor OnLockScreenStatus
  - [x] Refactor OnPermissionsChange
  - [x] Refactor OnSdlChoiceChosen
  - [x] Refactor OnSystemRequest
  - [x] Refactor OnTBTClientState
  - [x] Refactor OnTouchEvent
  - [x] Refactor OnVehicleData
  - [x] Refactor ParameterPermissions
  - [x] Refactor PerformAudioPassThru
  - [x] Refactor PerformAudioPassThruResponse
  - [x] Refactor PerformInteraction
  - [x] Refactor PerformInteractionResponse
  - [x] Refactor PermissionItem
  - [x] Refactor PresetBankCapabilities
  - [x] Refactor PutFile
  - [x] Refactor PutFileResponse
  - [x] Refactor ReadDID
  - [x] Refactor ReadDIDResponse
  - [x] Refactor RegisterAppInterface
  - [x] Refactor RegisterAppInterfaceResponse
  - [x] Refactor ResetGlobalProperties
  - [x] Refactor ResetGlobalPropertiesResponse
  - [x] Refactor ScreenParams
  - [x] Refactor ScrollableMessage
  - [x] Refactor ScrollableMessageResponse
  - [x] Refactor SdlMsgVersion
  - [x] Refactor SetAppIcon
  - [x] Refactor SetAppIconResponse
  - [x] Refactor SetDisplayLayout
  - [x] Refactor SetDisplayLayoutResponse
  - [x] Refactor SetGlobalProperties
  - [x] Refactor SetGlobalPropertiesResponse
  - [x] Refactor SetMediaClockTimer
  - [x] Refactor SetMediaClockTimerResponse
  - [x] Refactor Show
  - [x] Refactor ShowResponse
  - [x] Refactor SingleTireStatus
  - [x] Refactor Slider
  - [x] Refactor SliderResponse
  - [x] Refactor SoftButton
  - [x] Refactor SoftButtonCapabilities
  - [x] Refactor Speak
  - [x] Refactor SpeakResponse
  - [x] Refactor StartTime
  - [x] Refactor SubscribeButton
  - [x] Refactor SubscribeButtonResponse
  - [x] Refactor SubscribeVehicleData
  - [x] Refactor SubscribeVehicleDataResponse
  - [x] Refactor SystemRequest
  - [x] Refactor SystemRequestResponse
  - [x] Refactor TextField
  - [x] Refactor TireStatus
  - [x] Refactor TouchCoord
  - [x] Refactor TouchEvent
  - [x] Refactor TouchEventCapabilities
  - [x] Refactor TTSChunk
  - [x] Refactor UnregisterAppInterface
  - [x] Refactor UnregisterAppInterfaceResponse
  - [x] Refactor UnsubscribeButton
  - [x] Refactor UnsubscribeButtonResponse
  - [x] Refactor UnsubscribeVehicleData
  - [x] Refactor UnsubscribeVehicleDataResponse
  - [x] Refactor VehicleDataResult
  - [x] Refactor VehicleType
  - [x] Refactor VrHelpItem
- [x] Refactor RPC Enums
  - [x] Refactor AmbientLightStatus
  - [x] Refactor AppHMIType
  - [x] Refactor AppInterfaceUnregisteredReason
  - [x] Refactor AudioStreamingState
  - [x] Refactor AudioType
  - [x] Refactor BitsPerSample
  - [x] Refactor ButtonEventMode
  - [x] Refactor ButtonName
  - [x] Refactor ButtonPressMode
  - [x] Refactor CarModeStatus
  - [x] Refactor CharacterSet
  - [x] Refactor CompassDirection
  - [x] Refactor ComponentVolumeStatus
  - [x] Refactor DeviceLevelStatus
  - [x] Refactor Dimension
  - [x] Refactor DisplayType
  - [x] Refactor DriverDistractionState
  - [x] Refactor ECallConfirmationStatus
  - [x] Refactor EmergencyEventType
  - [x] Refactor FileType
  - [x] Refactor FuelCutoffStatus
  - [x] Refactor GlobalProperty
  - [x] Refactor HMILevel
  - [x] Refactor HmiZoneCapabilities
  - [x] Refactor IgnitionStableStatus
  - [x] Refactor IgnitionStatus
  - [x] Refactor ImageFieldName
  - [x] Refactor ImageType
  - [x] Refactor InteractionMode
  - [x] Refactor KeyboardEvent
  - [x] Refactor KeyboardLayout
  - [x] Refactor KeypressMode
  - [x] Refactor Language
  - [x] Refactor LayoutMode
  - [x] Refactor LockScreenStatus
  - [x] Refactor MediaClockFormat
  - [x] Refactor PowerModeQualificationStatus
  - [x] Refactor PowerModeStatus
  - [x] Refactor PrerecordedSpeech
  - [x] Refactor PrimaryAudioSource
  - [x] Refactor PRNDL
  - [x] Refactor RequestType
  - [x] Refactor Result
  - [x] Refactor SamplingRate
  - [x] Refactor SdlCommand
  - [x] Refactor SoftButtonType
  - [x] Refactor SpeechCapabilities
  - [x] Refactor SystemAction
  - [x] Refactor SystemContext
  - [x] Refactor TBTState
  - [x] Refactor TextAlignment
  - [x] Refactor TextFieldName
  - [x] Refactor TouchType
  - [x] Refactor TriggerSource
  - [x] Refactor UpdateMode
  - [x] Refactor VehicleDataEventStatus
  - [x] Refactor VehicleDataNotificationStatus
  - [x] Refactor VehicleDataResultCode
  - [x] Refactor VehicleDataStatus
  - [x] Refactor VehicleDataType
  - [x] Refactor VrCapabilities
  - [x] Refactor WarningLightStatus
  - [x] Refactor WiperStatus

### CODE REVIEW

**Comment by mikeburke106** [comment]
:grinning: :grinning: :grinning:  This PR is ready for testing!!  :grinning: :grinning: :grinning:

I've given it a quick test run on my Gen3 setup and it seems to be working pretty well.  Tomorrow, I'm going to run it through the unit tests that are in PR #68, which should give us a good idea as to how it works compared to the current code base.  I'm sure there are a couple bugs or typos that I've missed, but unit testing should be able to help me find those.

I will need someone setup with older versions of SDL (prior to gen 3) to give it a test run and make sure it works as expected.  @lea255ace, is that something you might be able to do?

Also, as you can see at the top, this PR has modified ~11,000 lines of code, so it's never too early to start reviewing the code.  This change is slated to be included in the 4.0.0 release on 3/31.

**Comment by mikeburke106** [comment]
[Here is a pre-built APK of the Livio SDL Tester built with this PR.](https://drive.google.com/file/d/0B3St2c_TV04WdVpYT0l0aUJ5OE0/view?usp=sharing)  Please use this file for testing.

**Comment by lea255ace** [comment]
Tested against a 1.1 TDK. The PutFile and SetAppIcon requests failed with 'UNSUPPORTED REQUEST' error codes, and the subsequent Show for the app icon fail with INVALID_DATA as a result. A manual Show to put text on the screen does work, however.

**Comment by mikeburke106** [comment]
Thanks, Mick.  I believe the "UNSUPPORTED_REQUEST" is expected since 1.1 doesn't support images.

I think the INVALID_DATA issue may be a bug in the tester app (unrelated to this PR).  Looks like I don't check if the PutFile was successful or not prior to deciding if I should send the image as part of the Show command, so the Show is failing due to graphic image not existing on the head-unit.  I'll make an issue for that in my repo.  I think this is also an inherent flaw with the Show command - if everything is good except for the image, the Show command should show whatever it can instead of rejecting the message outright.

Are the other supported commands (AddCommand, Alert, SubscribeButton, etc) working correctly?

**Comment by lea255ace** [comment]
Agreed on the Show behavior. The other commands work only somewhat. Alert will show the text for the alert, but the TTS fails and then the app disconnects. SubscribeButton and AddCommand similarly disconnect the app due to a timeout.

**Comment by mikeburke106** [comment]
The app is set up to disconnect whenever a request doesn't receive a response in a timely fashion (currently set to 5 seconds), so I'm guessing that's what's going on here.  This behavior could, potentially, be caused by this PR, but I'll have to do some digging.  Another possible cause could be if Gen1.1 is substantially slower on sending over responses, the app may be timing out before the response comes over.  I'll make a new APK of the app with this timeout disabled so we can try that.

Does a successful Show command receive a success response?

**Comment by lea255ace** [comment]
Nope, the text appears on the screen but no response ever shows up on the mobile side.

**Comment by mikeburke106** [comment]
Ok, that sounds incorrect, so I'll investigate.

**Comment by mikeburke106** [comment]
I made a few more modifications, so hopefully this fixes problems with Gen1.1.  [Here's a new APK to test with.](https://drive.google.com/file/d/0B3St2c_TV04Wd2t1eTNpUVRSWkk/view?usp=sharing)  I noticed that CreateInteractionChoiceSet isn't working correctly, so I need to investigate whether that's a problem with the application or with the PR.

Still working on getting unit tests up-and-running with this PR; once that is complete, I will be very confident in the status of this PR.

**Comment by mikeburke106** [comment]
Just tested most recent commit on Livio's Gen1.1 setup and it appears to be working correctly!  Can anyone else confirm?

Unit tests are looking excellent so far, I should be able to post a comparison to the current code base today.  Pending any additional bugs found during unit tests, this PR should be good to go.

**Comment by mikeburke106** [comment]
Here are the results of the unit tests for this PR.  Note that this PR needs to be re-based, so some issues have recently been fixed but are still showing failures.  These failed tests should pass after re-basing the branch.

Tests Run | Test Passes (%) | Test Failures (%) | Test Errors (%)
---------------|-------------------|-------------------|-----------------
1435 | 1312 (91%) | 110 (8%) | 13 (1%)

The difference between a test failure and a test error is that a failure successfully runs through the test code, but at least one of the test assertions was failed, while a test error crashes while executing the test code due to an exception that wasn't caught by the test.

Of the 123 failed tests, 83 are related to defensive-copying (#11), 17 are related to enums not handling valueForString consistently (#91),  10 are bugs in the mobile libraries (#71 & #102) and the remaining 13 are issues with the tests themselves.

You can compare these results against the master branch results [here](https://github.com/smartdevicelink/sdl_android/pull/88#issuecomment-73587138).  I'm still reviewing the results of the 1,400+ unit tests and looking for any additional bugs, but this PR actually has higher pass % than master, so it's in good shape!

**Comment by joeygrover** [comment]
Closing as stale.

**Pull request closed without merging**
