### PR TITLE
Implementation of lock screen icon via OnSystemRequest

### PR DESCRIPTION
**Pull request by mikeburke106**
Added new RequestType enum value for lock screen icon.  See #47 for more info.

Developers can now choose to download the icon at any time by calling `getLockScreenIcon` in SdlProxyBase.  This will either download the image from the OnSystemRequest URL or return the image directly if it has already been downloaded.

### CODE REVIEW

**Comment by ojmakke** [comment]
I see that LOCK_SCREEN_ICON_URL, "ends with comma" is followed directly by a ";"

**Comment by mikeburke106** [comment]
This is intentional and is [valid Java syntax](http://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.9).

The idea with this formatting is that if we need to add a new item into the enum, we don't have to modify the line containing the semicolon, we can simply add a new item with the comma at the end.  It turns a 2-3 line change into a 1 line change when the 2 files are compared, making the diff easier to read and compare.

Let's say we want to add an item to the following enum:

```java
public enum Number{
    ONE,
    TWO;
}
```

It would look something like this:

```java
public enum Number{
    ONE,
    TWO, // <-- had to delete the semicolon here and replace it with a comma
    THREE; // <-- added this line
}
```

Whereas, the way I formatted the semicolon would look like this:
```java
public enum Number{
    ONE,
    TWO,
    ;
}
```

And adding the new enum value looks like this:
```java
public enum Number{
   ONE,
   TWO,
   THREE, // <-- added this line
   ;
}
```

**Comment by joeygrover** [comment]
@justinjdickow need to confirm this works with latest SDL_CORE version

**Comment by justinjdickow** [comment]
Status: We confirmed that the system request is received by the application in the current version of core with this pull request.

Next Steps: is the developer facing portion of this pull request good to go in the proxy?

**Pull request merged**
