### PR TITLE
Feature/issue 559 - SDL Remote Control Baseline

### LINKED ISSUE #559: [SDL 0071] SDL Remote Control Baseline (no zones, no driver/passenger, immediate control)
Proposal: [SDL Remote Control Baseline (no zones, no driver/passenger, immediate control)](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0071-remote-control-baseline.md)

> SmartDeviceLink provides a framework that connects in-vehicle infotainment system to mobile phone applications. SDL enables a driver to interact with their mobile phone applications using common in-vehicle interfaces such as a touch screen display, embedded voice recognition, steering wheel controls and various vehicle knobs and buttons. Although SDL provides some RPCs to allow mobile applications to obtain some vehicle status information, it does not allow a mobile application to change the vehicle settings, i.e. to control the vehicle. SDL remote control (or previously known as reverse SDL) provides the ability for mobile applications to control certain settings of the vehicle, such as, radio and climate.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/206

Steering Committee Decision:

> Now that the requested revisions noted on the review issue have been incorporated, the Steering Committee has agreed to accept this proposal.

### PR DESCRIPTION
**Pull request by mrapitis**
Fixes #559

This PR is **ready** for review.

## Risk

This PR makes **minor** API changes.

## Testing Plan

Added new unit tests and expanded existing ones

## Summary

Added SDL Remote Control Baseline RPC's, structs, enums as defined in the proposal.

## CLA

- [x] I have signed the CLA

### CODE REVIEW

**Comment by mrapitis** [comment]
Do we want to move the newly introduced RPC's, structures, and enumerations that are specific to RC into their own package?   If so, we can certainly update the package structure to match the example provided, but in some cases it may make the package data structures less generic in the future.  For example, the TemperatureUnit enum lives inside of proxy/rc/enums in the example that you have provided, however this enumeration could well be a generic enumeration that applies to other RPC's (not RC specific) in the future as well.  Can you please provide more details in regards to how you envision the package structure for rc?  Specifically, we are interesting in knowing how to determine if an rpc, struct or enum should belong in the rc package vs the current generic package.
Thanks!

**Comment by joeygrover** [comment]
@mrapitis you bring up an excellent point. Maybe it doesn't make sense to move them into a separate package; we don't always know when one of the elements could be used beyond RC. I think any abstraction that we build would go into its own package off the `com.smartdevicelink.proxy` package, but I withdraw my change request to move the RPCs/Structs/Enums.

**Comment by brettywhite** [comment]
@mrapitis for the `RdsData` class is it necessary to abbreviate the names of the parameters? It seems like `setProgramService` instead of `setPs` would make developer's lives easier and enhance readability in the code.

**Comment by mrapitis** [comment]
@brettywhite updated, thanks.

**Comment by brettywhite** [comment]
@mrapitis in the `SystemCapability` Struct, are we missing the `remoteControlCapability` param? I'm trying to test this against the core PR and it looks like its missing that param per the evolution proposal.

**Comment by brettywhite** [comment]
Nevermind, having a case of the Mondays. Thanks

**Comment by mrapitis** [comment]
@brettywhite @joeygrover we have merged in the base branch so that this can be cleanly merged into develop.  Can you please let us know if anything is still pending to have the pr merged?
thanks

**Pull request merged**
