### PR TITLE
transport.enums package

### PR DESCRIPTION
**Pull request by MikaylaRay44**
See issue #194 for details.

### CODE REVIEW

**Comment by mrapitis** [comment]
Hi Mikayla,

Can you double check the imports on this pull request as well?  Some of the files have been changed to add imports without corresponding removals.

Thanks,
Markos

**Comment by MikaylaRay44** [comment]
For the `SdlConnection` class a bulk import was used for the transport package classes because it uses so many of them, but because the TransportType enum was moved to a different package namespace it would need to have a separate package import. I can't remove the bulk import because of the other dependencies, this specific import was added because the class moved locations otherwise it was covered in the bulk import as well.

As for the other transport package classes that did not have import removals like `BTTransport`,`BTTransportConfig`, etc. the TransportType class was previously in the same package as those classes so an extra import was not needed, but now it is in a new package namespace so it needs an import statement.

Even though we call the enums package a sub-package of the transport package there is no parental hierarchy between the two in Java so they are treated as completely different. That's all that's happening, I only added these statements where such errors occurred because of the move.

**Comment by mrapitis** [comment]
@MikaylaRay44 thanks for the follow up, have you also verified that no new warnings have been added to the project as a result of the changes?

**Comment by MikaylaRay44** [comment]
Yep, no warnings or suppressed warnings are seen on my end.

**Pull request merged**
