### PR TITLE
Multiplexing cleanup

### PR DESCRIPTION
**Pull request by joeygrover**
## Summary
This PR will involve several commits that will clean up some of the multiplexing integration. 

##### Handler Leaks
- [x] Transport Broker ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/bb772626adea92c57e004a52a414e5a234109ca0))
- [x] Router service (3) ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/05760b477d60193cce7fac7b5b94ed86fc6d2431))

##### Bug Fixes
- [x] Issue #328 ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/0b1809fb535e8774a0ac67a30e24f84c6f326b3b))
- [x] Fix how SdlPsm can crash with OOM exception if data size in packet header is wrong with way too many bytes ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/2cabad304948805f1da1a3262ce74fe73c875eb9))

##### Life cycle
- [x] Reduce repeat death notifications from binder death ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/560a49415fbb6272c5143b46f43f108d160cb9d9))
- [x] Remove client pinging when new client registers as it is causing lifecycle issues. ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/bf4ce5ae2b9e70af6ea36b1e84e37cf480bb01b4))

##### General 
- [x] Clean up logging ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/68f0299997373b1e93e7af622b25e4a2cd35efdc))
- [x] Remove unused Transport Constants ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/76b50403edf2731a1f29a0874cdbe934cc14c5a4))
- [x] Clean up disconnect intent filters in router service ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/590eab5e0e9aa1bd0865a7a69399a8b873c031f2))
- [x] Fix thread name in Multiplexing bluetooth transport. ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/f445345eccfe004f15bf65845b5bbc7a638390d6))
- [x] Change UUID record from SdlProxy to SdlRouterService to help with SDP look ups. ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/f445345eccfe004f15bf65845b5bbc7a638390d6))
- [x] Add a debug method to be able to extract the RPC hash from a packet. ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/4263ddb7124ba8f5fca707f9fb21f187f0861107))
- [x] Remove transport logging note ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/019b7e39f34c9df887b4adc78a983dfdb7f2c11f))
- [x] Only allow alt transport in debug mode. ([Commit](https://github.com/smartdevicelink/sdl_android/pull/330/commits/3688c6c1e3d60df91e0a795f3820a2699930a32a))

### CODE REVIEW

**Comment by jthrun** [comment]
Estimates on when this might be merged?

**Comment by joeygrover** [comment]
@mrapitis can you comment?

**Comment by mrapitis** [comment]
Early next week would be soonest as I'm out of the office until Monday.

**Comment by mrapitis** [comment]
lgtm

**Pull request merged**
