### PR TITLE
Feature/enhance video streaming

### PR DESCRIPTION
**Pull request by BrandonHe**
### Summary:
This PR is relative to #445, in order to enhance the video stream performance.

### In Depth:
In I/O operation, we're using class `PipedInputStream` and `PipedOutputStream`.  For writing thread, we found that data was written into buffer by each single Byte. After per byte was written into buffer, the reading thread was waked up (Thread state is changed from a blocked state to an executable state). It starts polling while the CPU is idle, run the read thread(Thread state is changed from an executable state to implementation state). 

But at this point, writing thread may occupy the critical resource of the thread, leading to read thread blocking(Thread state is changed from implementation state to blocking state). Frequently switch CPU state will reduce the CPU operating efficiency, and increase power consumption. 

In addition, read thread seize the critical resources in an inappropriate time will also reduce the efficiency of proxy transmission. For example, after write thread just writes a few bytes, almost at the same time, read thread gets the resources begin to read, the data in buffer will have to split into many frames to transmit.

So, we rewrite the class `PipedInputStream` and class `PipedOutputStream`, for more details, please reference #445 and modified codes.
### Performance Test:
**PC: Debian 32-bit, Windows 32-bit**
**Phone: Android4.4(XiaoMI mi3)**
**Connection: USB_AOA**
**Result:**
The data in test are false video stream data, aims to get the max value in transmission.

|             | SDL(Debian)|
|:---------|:------:|
|Proxy (**NOT** include this PR) | 1408.868Kb/s  |
|Proxy (**include** this PR)         | 2227.984Kb/s  |

|             | SDL(Windows)|
|:---------|:------:|
|Proxy (**NOT** include this PR) | 1.2Mb/s  |
|Proxy (**include** this PR)         | 7.5Mb/s  |

### CODE REVIEW

**Comment by BrandonHe** [comment]
@joeygrover 
Could you help to review this PR?
Thanks!

**Comment by joeygrover** [comment]
Hi Brandon,
In the future if you're PR is ready for review you can request a reviewer and we will get notified as well. However, looking at this PR I think this might need an evolution proposal. This PR is to basically create a custom implementation of a java class that we would have to support moving forward. I'd like to know if any other solutions were considered (different java classes, refactor code to not need pipes, etc). All of that could be explained and laid out in an evolution proposal. So before I can review and accept I would need to ensure the SDLC gets a chance to review the high level idea and approve.

**Comment by BrandonHe** [comment]
@joeygrover 
Hi Joey,
Thanks for your response. I'd like to create an evolution proposal if it's necessary. But for now, we don't have other solutions for this PR.

**Comment by joeygrover** [comment]
I don't feel as though I can review/merge this unless the SDLC accepts this as a proposal. You already have most of the info between the issue and the PR. So please submit a proposal with that information and if accepted I will review/merge this PR.

**Comment by chenbd** [comment]
@BrandonHe about video streaming performance, have you tried sending video data directly from encoder using byte buffer and handler instead of pipe to stream packetizer?
from my experience this will result in best performance.

**Comment by BrandonHe** [comment]
@joeygrover 
Thanks for your explanation! I will submit a proposal to ask SDLC to review first. 
Based on your information, can I understand that submit a proposal is our standard code contribution process?

**Comment by BrandonHe** [comment]
Hi @chenbd, Thanks for your suggestion, we have tried directly send encoder data using byte buffer, it doesn't have much improvement compared with this solution. I'm also afraid it will not be accepted by SDLC using byte buffer and handler to stream.

**Comment by joeygrover** [comment]
@BrandonHe[ this document ](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals_versus_issues.md)should help you determine when a PR should have a proposal or not. 

The improvement of just sending the packets straight from the encoder would be to avoid having to create our own custom pipe streams.

**Pull request closed without merging**
