### PR TITLE
Bugfix/issue 467

### PR DESCRIPTION
**Pull request by Tnnnguyen**
Fix issue [#467](https://github.com/smartdevicelink/sdl_android/issues/467)

This PR is **ready** for review.

### Risk
This PR makes **no** API changes.

### Testing Plan
Send null data to SendMessage method of WiProProtocol and test if it can handle.
New unit test passed.

### Summary
When data is null, SendMessage should not crash and should not attempt to send the message.

### CODE REVIEW

**Comment by brettywhite** [comment]
Hi @Tnnnguyen, we left you a message on the SDL slack. We have fixed the develop branch of this channel to have working CI and fixed unit tests. Can you please rebase or pull in the new develop for your PRs? Thank you

**Comment by Tnnnguyen** [comment]
Hi @brettywhite, I pull in the new develop.  Please let me know if it's ok. Thanks.

**Comment by brettywhite** [comment]
@Tnnnguyen It looks like the CI passed, so that worked. 👍  I know its sort of a pain but it will help us out a lot in keeping a clean repo. I won't comment on the other PRs but if you could do the same that would be great. Thank you.

**Comment by Tnnnguyen** [comment]
@brettywhite, yeah, I will do the same for other PR's.  Thanks.

**Pull request closed without merging**
